main:
  name: default
  seed: 42
  save_dir: artifacts/
  log_dir: logs/
  log_level: info
  overfit_batch: true
  logging: true
  
data: 
  data_path: data/
  workers: 16
  batch_size: 16
  subset: 0.03
  urban: true

transforms:
  sanitize_bb: false
  rpdist: [false, 1]
  rzout: [false, [123, 117, 104]]
  rioucrop: [false]
  rhflip: [false, 1]

model:
  lr: 3e-4
  pretrained: false
  optimizer: adam
  restore_from_ckpt:

training:
  devices: 1
  precision: 16-mixed
  epochs: 100

tracking:
  monitor: val_loss
  monitor_mode: max
  es_patience: 20 # early stopping patience
